USE QLTH

GO
CREATE TRIGGER NV_LUONG
ON dbo.NHANVIEN
FOR INSERT, UPDATE
AS
DECLARE
	@I_LUONG MONEY
BEGIN 
	SELECT @I_LUONG = Inserted.LUONG_NV
	FROM Inserted

	IF (@I_LUONG <= 0)
	BEGIN
		RAISERROR (N'LƯƠNG PHẢI LÀ MỘT SỐ NGUYÊN DƯƠNG', 16,1)
		ROLLBACK
	END
	COMMIT
END

GO
CREATE TRIGGER GV_LUONG
ON dbo.GIAOVIEN
FOR INSERT, UPDATE
AS
DECLARE
	@I_LUONG MONEY
BEGIN 
	SELECT @I_LUONG = Inserted.LUONG_GV
	FROM Inserted

	IF (@I_LUONG <= 0)
	BEGIN
		RAISERROR (N'LƯƠNG PHẢI LÀ MỘT SỐ NGUYÊN DƯƠNG', 16,1)
		ROLLBACK
	END
	COMMIT
END

GO
CREATE TRIGGER DIEMTHI_TN
ON dbo.DANHSACHTHI_TN
FOR INSERT, UPDATE
AS
BEGIN
	IF ((SELECT Inserted.DIEMTHI_TN FROM InserteD) < 0 OR (SELECT Inserted.DIEMTHI_TN FROM InserteD) > 10) 
		BEGIN
			RAISERROR (N'ĐIỂM KHÔNG HỢP LỆ',16,1)
			ROLLBACK
		END
	COMMIT
END

GO
CREATE TRIGGER MONHOC_HP
ON dbo.MONHOC
FOR INSERT, UPDATE
AS 
BEGIN
	IF ( (SELECT Inserted.HOCPHI FROM Inserted) <= 0)
	BEGIN
	    RAISERROR (N'HỌC PHÍ PHẢI LÀ SỐ NGUYÊN DƯƠNG', 16, 1)
		ROLLBACK
	END
	COMMIT
END

GO
CREATE TRIGGER SISOTOIDA
ON dbo.LOPHOC
FOR INSERT, UPDATE
AS
BEGIN
	IF ((SELECT Inserted.SISO_TOIDA FROM Inserted) <= 0)
		BEGIN
			RAISERROR (N'SỈ SỐ TỐI ĐA PHẢI LÀ MỘT SỐ NGUYÊN DƯƠNG', 16,1)
			ROLLBACK
		END
	COMMIT
END

GO
CREATE TRIGGER ADD_DKHP
ON dbo.CHITIET_DANGKYLOPHOC
FOR INSERT
AS
DECLARE
	@I_MALOP VARCHAR(50),
	@CURRENT INT,
	@MAX INT
BEGIN
	SELECT @I_MALOP = Inserted.MALOPHOC
	FROM Inserted

	SELECT @CURRENT = dbo.LOPHOC.SISO, @MAX = dbo.LOPHOC.SISO_TOIDA
	FROM dbo.LOPHOC

	IF (@CURRENT = @MAX)
	BEGIN
	    RAISERROR (N'LỚP ĐẦY',16, 1)
		ROLLBACK
	END
	ELSE
		BEGIN
			UPDATE dbo.LOPHOC
			SET SISO = SISO + 1
			WHERE MALOP = @I_MALOP
			COMMIT
		END
END

GO
CREATE TRIGGER DROP_DKHP
ON dbo.CHITIET_DANGKYLOPHOC
FOR DELETE
AS
DECLARE
	@I_MALOP VARCHAR(50)
BEGIN
	SELECT @I_MALOP = Deleted.MALOPHOC

	FROM Deleted

	UPDATE dbo.LOPHOC
	SET SISO = SISO - 1
	WHERE MALOP = @I_MALOP
	COMMIT
END

GO
CREATE TRIGGER HOADON_IUD
ON dbo.HOADON
FOR INSERT, UPDATE
AS
DECLARE	
	@CHUC_VU NVARCHAR(50)
BEGIN
	SELECT @CHUC_VU = NV.CHUCVU_NV
	FROM Inserted I JOIN dbo.NHANVIEN NV ON I.MANV = NV.MANV 

	IF(@CHUC_VU <> N'KẾ TOÁN' AND @CHUC_VU IS NOT NULL)
	BEGIN
		 RAISERROR (N'CHỈ CÓ NHÂN VIÊN KẾ TOÁN MỚI ĐƯỢC THỰC HIỆN', 16, 1)
		 ROLLBACK
	END
END

GO
CREATE TRIGGER HOADON_TONG_TIEN
ON dbo.HOADON
FOR INSERT, UPDATE
AS
BEGIN
    IF((SELECT Inserted.TONGTIEN FROM Inserted) <= 0)
	BEGIN
		RAISERROR (N'TỔNG TIỀN PHẢI LÀ MỘT SỐ NGUYÊN DƯƠNG',16, 1)
		ROLLBACK
	END
	COMMIT
END

GO
CREATE TRIGGER DTL
ON dbo.DANHSACH_THILAI
FOR INSERT, UPDATE
AS
BEGIN
	IF((SELECT Inserted.DIEMTHILAI FROM Inserted) < 0 OR (SELECT Inserted.DIEMTHILAI FROM Inserted) > 10)
	BEGIN
	    RAISERROR (N'ĐIỂM KHÔNG HỢP LỆ',16,1)
		ROLLBACK
	END
END

GO
CREATE TRIGGER DMH
ON dbo.DANHSACHTHI_MONHOC
FOR INSERT, UPDATE
AS
BEGIN
	IF((SELECT Inserted.DIEMTHI_MH FROM Inserted) < 0 OR (SELECT Inserted.DIEMTHI_MH FROM Inserted) > 10)
	BEGIN
	    RAISERROR (N'ĐIỂM KHÔNG HỢP LỆ',16,1)
		ROLLBACK
	END
END


