IF DB_ID ('QLTH') IS NOT NULL
	DROP DATABASE QLTH
CREATE DATABASE QLTH
USE QLTH
GO

CREATE TABLE NHANVIEN (
	MANV VARCHAR(50) NOT NULL,
	TENNV NVARCHAR(50) NOT NULL,
	LUONG_NV MONEY NOT NULL,
	DOB_NV DATE NOT NULL,
	DIACHI_NV NVARCHAR(100) NOT NULL,
	CHUCVU_NV NVARCHAR(50) NOT NULL,
	SDT_NV VARCHAR(10) NOT NULL UNIQUE,
	USERNAME_NV NVARCHAR(50) NOT NULL UNIQUE,

	CONSTRAINT PK_NV
	PRIMARY KEY (MANV)
)

CREATE TABLE GIAOVIEN (
	MAGV VARCHAR(50) NOT NULL,
	TENGV NVARCHAR(50) NOT NULL,
	LUONG_GV MONEY NOT NULL,
	DOB_NV DATE NOT NULL,
	DIACHI_GV NVARCHAR(100) NOT NULL,
	SDT_GV VARCHAR(10) NOT NULL UNIQUE,
	CHUYENMON_GV NVARCHAR(50) NOT NULL,
	HOCVI_GV NVARCHAR(20) NOT NULL,
	USERNAME_GV NVARCHAR(50) NOT NULL UNIQUE,
	

	CONSTRAINT PK_GV
	PRIMARY KEY (MAGV)
)

CREATE TABLE CT_DAOTAO (
	MA_CTDT VARCHAR(50),
	TEN_CTDT NVARCHAR(50) NOT NULL,
	THOIGIAN_KHAIGIANG DATE NOT NULL

	CONSTRAINT PK_CTDT
	PRIMARY KEY (MA_CTDT)
)

CREATE TABLE HOCVIEN (
	MAHV VARCHAR(50) NOT NULL,
	TENHV NVARCHAR(50) NOT NULL,
	DOB_HV DATE NOT NULL,
	DIACHI_HV VARCHAR(100) NOT NULL,
	SDT_HV VARCHAR(50) NOT NULL UNIQUE,
	USERNAME_HV NVARCHAR(50) NOT NULL UNIQUE,

	CONSTRAINT PK_HV
	PRIMARY KEY (MAHV)
)

CREATE TABLE BANGTOTNGHIEP (
	MABANG VARCHAR(50) NOT NULL,
	NGAYTOTNGHIEP DATE NOT NULL,
	LOAITN NVARCHAR(10) NOT NULL,
	MACTDT VARCHAR(50) NOT NULL,
	MAHV VARCHAR(50) NOT NULL

	CONSTRAINT PK_TN
	PRIMARY KEY (MABANG)
)

CREATE TABLE GHIDANH (
	MACTDT VARCHAR(50) NOT NULL,
	MAHV VARCHAR(50) NOT NULL,
	NGAYGHIDANH DATE NOT NULL

	CONSTRAINT PK_GD
	PRIMARY KEY (MACTDT, MAHV)
)

CREATE TABLE LICHTHI_TOTNGHIEP (
	MACTDT VARCHAR(50) NOT NULL,
	NGAYTHI_TN DATE NOT NULL,
	PHONGTHI_TN VARCHAR(10),
	CATHI_TN NVARCHAR(50)

	CONSTRAINT PK_LT_TN
	PRIMARY KEY (MACTDT, NGAYTHI_TN, CATHI_TN, PHONGTHI_TN)
)

CREATE TABLE DANHSACHTHI_TN (
	MACTDT VARCHAR(50) NOT NULL,
	NGAYTHI_TN DATE NOT NULL,
	CATHI_TN NVARCHAR(50) NOT NULL,
	PHONGTHI_TN VARCHAR(10),
	MAHV VARCHAR(50) NOT NULL,
	DIEMTHI_TN FLOAT NOT NULL

	CONSTRAINT PK_DS_TN
	PRIMARY KEY (MACTDT,NGAYTHI_TN,CATHI_TN,MAHV, PHONGTHI_TN)
)

CREATE TABLE MONHOC (
	MAMH VARCHAR(50) NOT NULL,
	TENMONHOC NVARCHAR(50) NOT NULL,
	HOCPHI MONEY NOT NULL,
	LOAI_MH NVARCHAR(20) NOT NULL

	CONSTRAINT PK_MH
	PRIMARY KEY (MAMH)
)

CREATE TABLE NHOMHOCPHAN (
	MANHOMHP VARCHAR(50) NOT NULL,
	TENNHOM_HP NVARCHAR(50) NOT NULL

	CONSTRAINT PK_HP
	PRIMARY KEY (MANHOMHP)
)

CREATE TABLE CHITIET_NHOMHP (
	MAHP VARCHAR(50) NOT NULL,
	MAMH VARCHAR(50) NOT NULL

	CONSTRAINT PK_CT_HP
	PRIMARY KEY (MAHP, MAMH)
)

CREATE TABLE LOPHOC (
	MALOP VARCHAR(50) NOT NULL,
	NGAYBATDAU DATE NOT NULL,
	NGAYKETTHUC DATE NOT NULL,
	PHONGHOC VARCHAR(10) NOT NULL,
	LICH_HOC NVARCHAR(50) NOT NULL,
	SISO_TOIDA INT NOT NULL,
	SISO INT NOT NULL,
	MAMH VARCHAR(50) NOT NULL,

	CONSTRAINT PK_LH
	PRIMARY KEY (MALOP)
)

CREATE TABLE PHANCONGDAY (
	MALOP VARCHAR(50),
	MAGV VARCHAR(50)

	CONSTRAINT PK_DAY
	PRIMARY KEY (MALOP, MAGV)
)

CREATE TABLE PHIEUDANGKY_LOPHOC (
	MAPHIEUDANGKY VARCHAR(50) NOT NULL,
	NGAYDANGKY_LOPHOC DATE NOT NULL,
	MAHV VARCHAR(50) NOT NULL

	CONSTRAINT PK_PDKLH
	PRIMARY KEY (MAPHIEUDANGKY)
)

CREATE TABLE CHITIET_DANGKYLOPHOC (
	MALOPHOC VARCHAR(50) NOT NULL,
	MAPHIEUDANKY_LOPHOC VARCHAR(50) NOT NULL,
	KETQUAMONHOC BIT 

	CONSTRAINT PK_CTDK
	PRIMARY KEY (MALOPHOC,MAPHIEUDANKY_LOPHOC)
)

CREATE TABLE HOADON (
	NGAYLAPHOADON DATE NOT NULL,
	MAPHIEUDANGKY_LOPHOC VARCHAR(50) NOT NULL,
	TONGTIEN MONEY NOT NULL,
	MANV VARCHAR(50) NOT NULL

	CONSTRAINT PK_HD
	PRIMARY KEY (MAPHIEUDANGKY_LOPHOC)
)

CREATE TABLE GIAYCHUNGNHAN (
	MAGCN VARCHAR(50) NOT NULL,
	TENGCN NVARCHAR(50) NOT NULL,
	MAHP VARCHAR(50) NOT NULL,
	MAHV VARCHAR(50) NOT NULL

	CONSTRAINT PK_GCN
	PRIMARY KEY (MAGCN)
)

CREATE TABLE LICHTHI_THILAI (
	MAMH VARCHAR(50) NOT NULL,
	NGAYTHILAI DATE,
	PHONGTHILAI VARCHAR(10),
	CATHILAI NVARCHAR(50),

	CONSTRAINT PK_TL
	PRIMARY KEY (MAMH,NGAYTHILAI,CATHILAI, PHONGTHILAI)
)

CREATE TABLE DANHSACH_THILAI (
	MAMH VARCHAR(50) NOT NULL,
	NGAYTHILAI DATE,
	MAHV VARCHAR(50),
	PHONGTHILAI VARCHAR(10),
	CATHILAI NVARCHAR(50),
	DIEMTHILAI FLOAT 

	CONSTRAINT PK_DS_TL
	PRIMARY KEY (MAMH, NGAYTHILAI, MAHV, CATHILAI, PHONGTHILAI)
)

CREATE TABLE LICHTHI_MONHOC (
	MALOPHOC VARCHAR(50) NOT NULL,
	PHANLOAI VARCHAR(20) NOT NULL,
	NGAYTHI_MONHOC DATE,
	PHONGTHI_MONHOC VARCHAR(10),
	CATHI_MONHOC NVARCHAR(50),

	CONSTRAINT PK_THI_MH
	PRIMARY KEY (MALOPHOC, NGAYTHI_MONHOC, PHONGTHI_MONHOC, CATHI_MONHOC)
)

CREATE TABLE DANHSACHTHI_MONHOC (
	MALOPHOC VARCHAR(50),
	NGAYTHI_MONHOC DATE,
	PHONGTHI_MONHOC VARCHAR(10),
	CATHI_MONHOC NVARCHAR(50),
	MAHV VARCHAR(50),
	DIEMTHI_MH FLOAT,

	CONSTRAINT PK_DS_MH
	PRIMARY KEY (NGAYTHI_MONHOC, PHONGTHI_MONHOC, CATHI_MONHOC, MAHV, MALOPHOC)
)

CREATE TABLE DANHSACH_GACTHI (
	NGAYTHI DATE,
	PHONGTHI VARCHAR(10),
	CATHI NVARCHAR(50),
	MANV VARCHAR(50)

	CONSTRAINT PK_DS_GACTHI
	PRIMARY KEY (NGAYTHI, PHONGTHI, CATHI,MANV)
)

CREATE TABLE LICHTHI (
	NGAYTHI DATE,
	PHONGTHI VARCHAR(10),
	CATHI NVARCHAR (50)

	CONSTRAINT PK_LICHTHI
	PRIMARY KEY (NGAYTHI, PHONGTHI, CATHI)
)

CREATE TABLE USERS (
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	TYPE VARCHAR(20)
)

ALTER TABLE dbo.BANGTOTNGHIEP
ADD
 CONSTRAINT FK_TN_DT
 FOREIGN KEY (MACTDT)
 REFERENCES dbo.CT_DAOTAO,

 CONSTRAINT FK_TN_HV
 FOREIGN KEY (MAHV)
 REFERENCES dbo.HOCVIEN

ALTER TABLE dbo.GHIDANH
ADD
	CONSTRAINT FK_GD_DT
	FOREIGN KEY (MACTDT)
	REFERENCES dbo.CT_DAOTAO,

	CONSTRAINT FK_DT_HV
	FOREIGN KEY (MAHV)
	REFERENCES dbo.HOCVIEN

ALTER TABLE dbo.LICHTHI_TOTNGHIEP
ADD
	CONSTRAINT FK_LTTN_DT
	FOREIGN KEY (MACTDT)
	REFERENCES dbo.CT_DAOTAO

ALTER TABLE dbo.LICHTHI_TOTNGHIEP
ADD
	CONSTRAINT FK_LT_TN
	FOREIGN KEY (NGAYTHI_TN,PHONGTHI_TN, CATHI_TN)
	REFERENCES LICHTHI

ALTER TABLE dbo.DANHSACHTHI_TN 
ADD 
	CONSTRAINT FK_DSTN_LTTN
	FOREIGN KEY(MACTDT,NGAYTHI_TN,CATHI_TN, PHONGTHI_TN)
	REFERENCES dbo.LICHTHI_TOTNGHIEP,

	CONSTRAINT FK_DSTN_HV
	FOREIGN KEY (MAHV)
	REFERENCES dbo.HOCVIEN

ALTER TABLE dbo.CHITIET_NHOMHP
ADD
	CONSTRAINT FK_CTHP_HP
	FOREIGN KEY (MAHP)
	REFERENCES dbo.NHOMHOCPHAN,

	CONSTRAINT FK_CTHP_MH
	FOREIGN KEY (MAMH)
	REFERENCES dbo.MONHOC

ALTER TABLE dbo.LOPHOC
ADD 
	CONSTRAINT FK_LH_MH
	FOREIGN KEY (MAMH)
	REFERENCES dbo.MONHOC

ALTER TABLE dbo.PHANCONGDAY
ADD 
	CONSTRAINT FK_PC_LH
	FOREIGN KEY(MALOP)
	REFERENCES dbo.LOPHOC,

	CONSTRAINT FK_PC_GV
	FOREIGN KEY (MAGV)
	REFERENCES dbo.GIAOVIEN

ALTER TABLE dbo.CHITIET_DANGKYLOPHOC
ADD
	CONSTRAINT FK_DKHP_LH
	FOREIGN KEY (MALOPHOC)
	REFERENCES dbo.LOPHOC,

	CONSTRAINT FK_CT_PDK
	FOREIGN KEY (MAPHIEUDANKY_LOPHOC)
	REFERENCES dbo.PHIEUDANGKY_LOPHOC

ALTER TABLE dbo.GIAYCHUNGNHAN
ADD
	CONSTRAINT FK_GCN_HP
	FOREIGN KEY (MAHP)
	REFERENCES dbo.NHOMHOCPHAN,

	CONSTRAINT FK_GCN_HV
	FOREIGN KEY (MAHV)
	REFERENCES dbo.HOCVIEN

ALTER TABLE dbo.LICHTHI_THILAI
ADD 
	CONSTRAINT FK_TL_MH
	FOREIGN KEY (MAMH)
	REFERENCES dbo.MONHOC,

	CONSTRAINT FK_LT_MH
	FOREIGN KEY (NGAYTHILAI, PHONGTHILAI, CATHILAI)
	REFERENCES LICHTHI

ALTER TABLE dbo.DANHSACH_THILAI
ADD 
	CONSTRAINT FK_DSTL_HV
	FOREIGN KEY (MAHV)
	REFERENCES HOCVIEN,

	CONSTRAINT FK_LTL
	FOREIGN KEY (MAMH, NGAYTHILAI, CATHILAI, PHONGTHILAI)
	REFERENCES dbo.LICHTHI_THILAI

ALTER TABLE dbo.LICHTHI_MONHOC
ADD		
	CONSTRAINT FK_LT_LH
	FOREIGN KEY (MALOPHOC)
	REFERENCES dbo.LOPHOC,

	CONSTRAINT FK_LTMH
	FOREIGN KEY (NGAYTHI_MONHOC, PHONGTHI_MONHOC, CATHI_MONHOC)
	REFERENCES LICHTHI

ALTER TABLE dbo.DANHSACHTHI_MONHOC
ADD		

	CONSTRAINT FK_DSMH_HV
	FOREIGN KEY (MAHV)
	REFERENCES dbo.HOCVIEN, 

	CONSTRAINT FK_DSTMH
	FOREIGN KEY (MALOPHOC, NGAYTHI_MONHOC, PHONGTHI_MONHOC, CATHI_MONHOC)
	REFERENCES LICHTHI_MONHOC

ALTER TABLE dbo.HOADON
ADD
	CONSTRAINT FK_HD_NV
	FOREIGN KEY (MANV)
	REFERENCES dbo.NHANVIEN,

	CONSTRAINT FK_HD_DKHP
	FOREIGN KEY (MAPHIEUDANGKY_LOPHOC)
	REFERENCES dbo.PHIEUDANGKY_LOPHOC

ALTER TABLE dbo.PHIEUDANGKY_LOPHOC
ADD 
	CONSTRAINT FK_DKHP_HV
	FOREIGN KEY (MAHV)
	REFERENCES dbo.HOCVIEN

ALTER TABLE DANHSACH_GACTHI
ADD
	CONSTRAINT FK_GT_LT
	FOREIGN KEY (NGAYTHI, PHONGTHI, CATHI)
	REFERENCES LICHTHI

GO
CREATE TRIGGER FK_DSGT_MANV
ON dbo.DANHSACH_GACTHI
AFTER INSERT,DELETE
AS
DECLARE
	@CURRENT_MANV VARCHAR (50) = NULL
BEGIN
	SELECT @CURRENT_MANV = dbo.NHANVIEN.MANV 
	FROM dbo.NHANVIEN, Inserted
	WHERE dbo.NHANVIEN.MANV = Inserted.MANV

	IF (@CURRENT_MANV IS NULL)
	BEGIN
		SELECT @CURRENT_MANV = dbo.GIAOVIEN.MAGV
		FROM dbo.GIAOVIEN , Inserted
		WHERE dbo.GIAOVIEN.MAGV = Inserted.MANV

		IF (@CURRENT_MANV IS NULL)
			BEGIN
				RAISERROR (N'MANV KHÔNG TỒN TẠI', 16,1)
				ROLLBACK
			END
	END
END



